export enum WeatherCondition {
  ClearDay = 'clear-day',
  PartlyCloudy = 'partly-cloudy',
  Cloudy = 'cloudy',
  Fog = 'fog',
  LightPrecipitation = 'light-precipitation',
  HeavyPrecipitation = 'heavy-precipitation',
  ExtremeConditions = 'extreme-conditions',
  IceConditions = 'ice-conditions',
}

export const weatherCodeMap: { [code: number]: WeatherCondition } = {
  1000: WeatherCondition.ClearDay,
  113: WeatherCondition.ClearDay,
  1003: WeatherCondition.PartlyCloudy,
  116: WeatherCondition.PartlyCloudy,
  1006: WeatherCondition.Cloudy,
  1009: WeatherCondition.Cloudy,
  119: WeatherCondition.Cloudy,
  122: WeatherCondition.Cloudy,
  1030: WeatherCondition.Fog,
  1135: WeatherCondition.Fog,
  1147: WeatherCondition.Fog,
  143: WeatherCondition.Fog,
  248: WeatherCondition.Fog,
  260: WeatherCondition.Fog,
  1063: WeatherCondition.LightPrecipitation,
  1066: WeatherCondition.LightPrecipitation,
  1069: WeatherCondition.IceConditions,
  1072: WeatherCondition.IceConditions,
  1087: WeatherCondition.ExtremeConditions,
  1114: WeatherCondition.ExtremeConditions,
  1117: WeatherCondition.ExtremeConditions,
  1150: WeatherCondition.LightPrecipitation,
  1153: WeatherCondition.LightPrecipitation,
  1168: WeatherCondition.IceConditions,
  1171: WeatherCondition.IceConditions,
  1180: WeatherCondition.LightPrecipitation,
  1183: WeatherCondition.LightPrecipitation,
  1186: WeatherCondition.HeavyPrecipitation,
  1189: WeatherCondition.HeavyPrecipitation,
  1192: WeatherCondition.HeavyPrecipitation,
  1195: WeatherCondition.HeavyPrecipitation,
  1198: WeatherCondition.IceConditions,
  1201: WeatherCondition.IceConditions,
  1204: WeatherCondition.IceConditions,
  1207: WeatherCondition.IceConditions,
  1210: WeatherCondition.LightPrecipitation,
  1213: WeatherCondition.LightPrecipitation,
  1216: WeatherCondition.LightPrecipitation,
  1219: WeatherCondition.HeavyPrecipitation,
  1222: WeatherCondition.HeavyPrecipitation,
  1225: WeatherCondition.HeavyPrecipitation,
  1237: WeatherCondition.LightPrecipitation,
  1240: WeatherCondition.LightPrecipitation,
  1243: WeatherCondition.HeavyPrecipitation,
  1246: WeatherCondition.HeavyPrecipitation,
  1249: WeatherCondition.IceConditions,
  1252: WeatherCondition.IceConditions,
  1255: WeatherCondition.LightPrecipitation,
  1258: WeatherCondition.HeavyPrecipitation,
  1261: WeatherCondition.LightPrecipitation,
  1264: WeatherCondition.HeavyPrecipitation,
  1273: WeatherCondition.LightPrecipitation,
  1276: WeatherCondition.HeavyPrecipitation,
  1279: WeatherCondition.LightPrecipitation,
  1282: WeatherCondition.HeavyPrecipitation,
  227: WeatherCondition.ExtremeConditions,
  230: WeatherCondition.ExtremeConditions,
  350: WeatherCondition.IceConditions,
  353: WeatherCondition.LightPrecipitation,
  356: WeatherCondition.HeavyPrecipitation,
  359: WeatherCondition.HeavyPrecipitation,
  368: WeatherCondition.LightPrecipitation,
  371: WeatherCondition.HeavyPrecipitation,
  374: WeatherCondition.LightPrecipitation,
  377: WeatherCondition.HeavyPrecipitation,
  386: WeatherCondition.LightPrecipitation,
  389: WeatherCondition.HeavyPrecipitation,
  392: WeatherCondition.LightPrecipitation,
  395: WeatherCondition.HeavyPrecipitation,
};
