// Generated by https://quicktype.io

export interface City {
    id:      number;
    name:    string;
    region:  string;
    country: string;
    lat:     number;
    lon:     number;
    url:     string;
}
